### ISSUE TITLE
Unable to run the Shazam Recognizer

### ISSUE THREAD

**Issue by Ekta-Shah** [Numenorean/ShazamAPI#1]
Hi,

I tried running the following code:
from ShazamAPI import Shazam

mp3_file_content_to_recognize = open('2_com.mp3', 'rb').read()
shazam = Shazam(mp3_file_content_to_recognize)
recognize_generator = shazam.recognizeSong()
while True:
    print(next(recognize_generator))

I am getting the following error:

SSLError: HTTPSConnectionPool(host='amp.shazam.com', port=443): Max retries exceeded with url: /discovery/v5/ru/RU/iphone/-/tag/655074ED-134F-4831-8C92-89B8111F1EE5/7ADBDBAD-37B8-4957-B69E-9B7E2B53158D?sync=true&webv3=true&sampling=true&connected=&shazamapiversion=v3&sharehub=true&hubv5minorversion=v5.1&hidelb=true&video=v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

I am unable to resolve this. Can you please help? @Numenorean

**Comment by Numenorean** [comment]
You should disable all traffic sniffers, or modify all lines in api.py that has requests.get or requests.post methods, and add argument verify=False

**Comment by Ekta-Shah** [comment]
Thank you @Numenorean. Works fine now.
