### ISSUE TITLE
Question: Max request number

### ISSUE THREAD

**Issue by ommex** [Numenorean/ShazamAPI#4]
Hello, is there any limit how often I can run the script? Something like a request limit per IP?

**Comment by Numenorean** [comment]
Hi, can't say for sure, but as I know, shazam doesn't limit requests per second/per ip. I've tested it with burp suite intruder, made ~1k requests per 40s, with static and valid song signature ![](https://i.imgur.com/ugq2r2V.png)

**Comment by ommex** [comment]
Okay, Thanks!
