### ISSUE TITLE
Refactoring proposal

### ISSUE THREAD

**Issue by notpushkin** [Numenorean/ShazamAPI#7]
First of all, thank you for your wonderful work!

I'm currently linting some of your code – removing extraneous whitespace, tweaking code style (`camelCase` -> `snake_case`, etc), moving some hardcoded values out as constants (where it makes sense) etc. I'm largely using https://wemake-python-stylegui.de/ as a guide, but adding a lot of exceptions where it makes sense. You can see the documentation on [the rules it recommends](https://wemake-python-stylegui.de/en/latest/pages/usage/violations/index.html), it is really well written.

I then plan to tweak the API to allow passing a `pydub.AudioSegment` directly and be more flexible overall. Would you be interested in accepting a PR with these changes?

**Comment by notpushkin** [comment]
You can see my changes [here](https://github.com/notpushkin/ShazamAPI/tree/refactor) ([compare](https://github.com/Numenorean/ShazamAPI/compare/main...notpushkin:refactor)).

It's a big change, so perhaps go commit by commit. I can open a PR if you want to review / discuss it.

**Comment by Numenorean** [comment]
Yep, it's looks pretty good. If you open a PR, I will check it tomorrow and merge
